### PR TITLE
Fallback to find key in element value

### PR DESCRIPTION
**Pull request by rehleinBo**
If the plugin fails in any case. The keys are displayed instead of nothing.

### CODE REVIEW

**Comment by atticoos** [comment]
Great call -- a fallback could be very useful here.

**Comment by atticoos** [comment]
Correct me if I'm wrong, but it appears that this is to support a scenario where no key is provided in the `translate-once=""` attribute?

In this scenario, wouldn't it be better to just stop early and avoid an attempt to translate since there's nothing to translate?

I also wonder about the scenario where the key is supplied, but there's no entry

**Comment by rehleinBo** [comment]
First if all. Please excuse my bad English. 

You are right. Today at work we had a little argument about this and I was on your side.

My colleagues argument was, that in case of a failure or another error the ui would display the translation keys.
When the key is set via the attribute value the ui will be empty.
The second one is that 'angular-translate' supports the same behavior.

We did this change today for a new project and I thought that this change could be useful. It doesn't destroy anything from my point of view.

I will not be mad if you reject the request. :-)
As long as I can use your great enhamcement of angular-translate for me with my little tweak.

Am 5. Januar 2016 23:22:43 MEZ, schrieb Atticus White notifications@github.com:

**Comment by atticoos** [comment]
> The second one is that 'angular-translate' supports the same behavior.

This right here is the most convincing thing to me. I think the goal of this project should be to provide the exact same behavior as the core module, with the added benefit of one-time bindings.

If `angular-translate` behaves this way, this should as well.

Thank you for your response! I'm going to do some exploration of these edge cases with `angular-translate` and I'll get back to you :smile: 

PS - your English is just fine :ok_hand:

**Comment by atticoos** [comment]
I'm going to merge this and make a few changes and clean up the failing build. For instance, I don't think we need to do anything if there is no key -- just leave the element as it is.

Thanks for this contribution! It has sparked a few ideas in how to better handle _missing_ translations. I've opened #10 to track that issue.

**Comment by atticoos** [comment]
Ah - actually, I see what you did. You are supporting scenarios where the translation key is the actual text value of the element. Got it.

Little communication problem. Your PR is good :+1:

**Comment by rehleinBo** [comment]
Thanks a lot for merging. :-)

Am 6. Januar 2016 02:22:14 MEZ, schrieb Atticus White notifications@github.com:

**Pull request merged**
